//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bicycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bicycle()
        {
            this.BicycleEntryHeaders = new HashSet<BicycleEntryHeader>();
        }
    
        public int ID { get; set; }
        public string NameOwner { get; set; }
        public string ContactNo { get; set; }
        public string BrandName { get; set; }
        public string IdentificationNo { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BicycleEntryHeader> BicycleEntryHeaders { get; set; }
    }
}
