//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireHydrantDetails
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int GlassCabinet { get; set; }
        public int Hanger { get; set; }
        public int Hose15 { get; set; }
        public int Nozzle15 { get; set; }
        public int Hose25 { get; set; }
        public int Nozzle25 { get; set; }
        public int SpecialTools { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public int FireHydrantHeaderId { get; set; }
        public string InspectedBy { get; set; }
        public string NotedBy { get; set; }
        public string ReviewedBy { get; set; }
        public string ImageUrl { get; set; }
        public int LocationFireHydrantId { get; set; }
    
        public virtual FireHydrantHeaders FireHydrantHeaders { get; set; }
        public virtual Items Items { get; set; }
        public virtual LocationFireHydrants LocationFireHydrants { get; set; }
    }
}
