//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemLogs = new HashSet<ItemLog>();
            this.LocationItemDetails = new HashSet<LocationItemDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public int Warranty { get; set; }
        public string ItemStatus { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public string EquipmentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLog> ItemLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationItemDetail> LocationItemDetails { get; set; }
    }
}
