//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.EmergencyLightDetails = new HashSet<EmergencyLightDetails>();
            this.FireExtinguisherDetails = new HashSet<FireExtinguisherDetails>();
            this.FireHydrantDetails = new HashSet<FireHydrantDetails>();
            this.InergenTankDetails = new HashSet<InergenTankDetails>();
            this.LocationItemDetails = new HashSet<LocationItemDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string ItemStatus { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public string EquipmentType { get; set; }
        public int IsIn { get; set; }
        public string Capacity { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyLightDetails> EmergencyLightDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireExtinguisherDetails> FireExtinguisherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireHydrantDetails> FireHydrantDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InergenTankDetails> InergenTankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationItemDetails> LocationItemDetails { get; set; }
    }
}
