//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationItemDetails
    {
        public int Id { get; set; }
        public string Equipment { get; set; }
        public int HeaderId { get; set; }
        public int ItemId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
