//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationFireExtinguishers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationFireExtinguishers()
        {
            this.FireExtinguisherDetails = new HashSet<FireExtinguisherDetails>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Code { get; set; }
        public int AreaId { get; set; }
        public string Status { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FireExtinguisherDetails> FireExtinguisherDetails { get; set; }
    }
}
