//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationInergenTank
    {
        public int Id { get; set; }
        public string Capacity { get; set; }
        public string Serial { get; set; }
        public string Area { get; set; }
        public int AreaId { get; set; }
        public string Status { get; set; }
    
        public virtual Area Area1 { get; set; }
    }
}
