//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEMEntities : DbContext
    {
        public SEMEntities()
            : base("name=SEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<BicycleEntryDetails> BicycleEntryDetails { get; set; }
        public virtual DbSet<BicycleEntryHeaders> BicycleEntryHeaders { get; set; }
        public virtual DbSet<Bicycles> Bicycles { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EmergencyLightDetails> EmergencyLightDetails { get; set; }
        public virtual DbSet<EmergencyLightHeaders> EmergencyLightHeaders { get; set; }
        public virtual DbSet<FireExtinguisherDetails> FireExtinguisherDetails { get; set; }
        public virtual DbSet<FireExtinguisherHeaders> FireExtinguisherHeaders { get; set; }
        public virtual DbSet<FireHydrantDetails> FireHydrantDetails { get; set; }
        public virtual DbSet<FireHydrantHeaders> FireHydrantHeaders { get; set; }
        public virtual DbSet<InergenTankDetails> InergenTankDetails { get; set; }
        public virtual DbSet<InergenTankHeaders> InergenTankHeaders { get; set; }
        public virtual DbSet<ItemLogs> ItemLogs { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<LocationEmergencyLights> LocationEmergencyLights { get; set; }
        public virtual DbSet<LocationFireExtinguishers> LocationFireExtinguishers { get; set; }
        public virtual DbSet<LocationFireHydrants> LocationFireHydrants { get; set; }
        public virtual DbSet<LocationInergenTanks> LocationInergenTanks { get; set; }
        public virtual DbSet<LocationItemDetails> LocationItemDetails { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<NoSeries> NoSeries { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
