//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMSystemApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEMEntities : DbContext
    {
        public SEMEntities()
            : base("name=SEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<BicycleEntryDetail> BicycleEntryDetails { get; set; }
        public virtual DbSet<BicycleEntryHeader> BicycleEntryHeaders { get; set; }
        public virtual DbSet<Bicycle> Bicycles { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmergencyLightDetail> EmergencyLightDetails { get; set; }
        public virtual DbSet<EmergencyLightHeader> EmergencyLightHeaders { get; set; }
        public virtual DbSet<FireExtinguisherDetail> FireExtinguisherDetails { get; set; }
        public virtual DbSet<FireExtinguisherHeader> FireExtinguisherHeaders { get; set; }
        public virtual DbSet<FireHydrantDetail> FireHydrantDetails { get; set; }
        public virtual DbSet<FireHydrantHeader> FireHydrantHeaders { get; set; }
        public virtual DbSet<InergenTankDetail> InergenTankDetails { get; set; }
        public virtual DbSet<InergenTankHeader> InergenTankHeaders { get; set; }
        public virtual DbSet<ItemLog> ItemLogs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<LocationEmergencyLight> LocationEmergencyLights { get; set; }
        public virtual DbSet<LocationFireExtinguisher> LocationFireExtinguishers { get; set; }
        public virtual DbSet<LocationFireHydrant> LocationFireHydrants { get; set; }
        public virtual DbSet<LocationInergenTank> LocationInergenTanks { get; set; }
        public virtual DbSet<LocationItemDetail> LocationItemDetails { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<NoSery> NoSeries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
